### ISSUE TITLE
Logical Error in ValueComparator 

### ISSUE THREAD

**Issue by chinnonae** [OOP2018/coinpurse-KameriiJ#8]
The values are compared only when currencies are the same. If the currencies are different, you have to compare them instead.  

![image](https://user-images.githubusercontent.com/11190475/35895717-3b86e248-0beb-11e8-8b5a-d405991a62f4.png)

https://github.com/OOP2018/coinpurse-KameriiJ/blob/296baba89edd686a5c73924a57e5b5031733af3e/src/coinpurse/ValueComparator.java#L12-L18

**Comment by Gunzther** [comment]
ไม่เข้าใจการ compare them by currency ค่ะ ถ้าเทียบแล้วสกุลเงินมันไม่เหมือนกัน หนูต้องเรียงตามตัวอักษรตัวแรกของสกุลเงินหรอคะ แบบ Baht กับ Dollar B มาก่อน D ก็ return -1 ??

**Comment by taveratch** [comment]
Exactly, B comes before D then it should return a negative number. 
If a = Yuen and b = Yen, what should it return?
